name: Mi primer pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar el codigo
        uses: actions/checkout@v4

      - name: Simular un test
        run: |
          echo "Corriendo tests..."
          echo "Test 1 - OK"
          echo "Test 2 - OK"
          echo "Todos los tests pasaron!"

      - name: Paso que falla a proposito
        run: |
          echo "Este paso va a fallar..."
          exit 1

      - name: Este paso nunca va a correr
        run: |
          echo "Nunca vas a ver esto"
