name: Mi primer pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MI_PASSWORD: ${{ secrets.MI_PASSWORD }}
    steps:
      - name: Bajar el codigo
        uses: actions/checkout@v4

      - name: Usar el secret
        run: |
          echo "Intentando imprimir el secret:"
          echo $MI_PASSWORD
          echo "GitHub lo oculta automaticamente!"

      - name: Bypass del filtro con base64
        run: |
          echo "Secret en base64:"
          echo $MI_PASSWORD | base64
